version: "3.8"

services:

  app:
    build: .
    restart: always
    volumes:
      - './db:/usr/src/app/db:rw'
    ports:
      - 8000:8000
    environment:
      - TZ=Europe/Kiev
      - PYTHONUNBUFFERED=1